// AUTO-GENERATED by scripts/import_guga_feed.py. Do not edit by hand.
export type KidsCategory = { slug: string; name: string; count: number };

export const KIDS_CATEGORIES: KidsCategory[] = [
  {
    "name": "Мебели",
    "slug": "mebeli",
    "count": 120
  }
];
